name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Test lint
        run: yarn lint

      - name: Test build
        run: yarn build
